export const ISSUE_KEYS = ["restricted", "lost_access", "email_code", "password_changed", "email_removed", "two_factor", "other"] as const;
export type AccountIssue = typeof ISSUE_KEYS[number];
export const ACCOUNT_ISSUES: Record<AccountIssue, { label: string; problem: string; steps: string }> = {
  restricted: { label: "Restricted by LinkedIn", problem: "LinkedIn has restricted the account.", steps: "1. Sign in through LinkedIn's official app or website.\n2. Follow the recovery or identity-verification instructions LinkedIn displays.\n3. Reply once the restriction is cleared, or tell us what message LinkedIn displays if you need help." },
  lost_access: { label: "Lost access to the account", problem: "Our team can no longer access the account.", steps: "1. Check whether the account owner can sign in to LinkedIn.\n2. Let us know whether any login, email, or security settings have changed.\n3. Reply so we can arrange the next steps to restore our access." },
  email_code: { label: "Verification email / code not arriving", problem: "The verification email or code needed to access the account is not arriving.", steps: "1. Check the account's email addresses in LinkedIn Settings & Privacy → Sign in & security.\n2. Confirm that the LinkedVelocity email address is still added and verified.\n3. Check spam/junk folders for verification emails and tell us which address LinkedIn is sending them to.\n4. Reply with what you find so we can restore access." },
  password_changed: { label: "Password changed or not working", problem: "The saved password no longer works, so our team cannot sign in.", steps: "1. Check that the account owner can sign in and whether the password was recently changed.\n2. If necessary, use LinkedIn's official password-reset process.\n3. Reply to arrange a secure update of the login details with our team." },
  email_removed: { label: "LinkedVelocity email removed / not primary", problem: "The LinkedVelocity email address is missing or is no longer the primary email on the account.", steps: "1. Open LinkedIn Settings & Privacy → Sign in & security → Email addresses.\n2. Check that the LinkedVelocity email address is listed and verified. If it is missing, reply so we can confirm the correct address and coordinate adding it.\n3. Set the confirmed LinkedVelocity email as primary and let us know when it is done." },
  two_factor: { label: "Two-factor authentication issue", problem: "The account's two-factor authentication is preventing our team from signing in.", steps: "1. Check whether the account owner can sign in using their authenticator or LinkedIn's official recovery process.\n2. Tell us whether the authenticator or two-factor settings recently changed.\n3. Reply so we can coordinate a secure update and verify access together." },
  other: { label: "Other", problem: "There is an issue with the account that needs to be resolved.", steps: "Please address the issue described above and reply when it is resolved, or let us know what help you need." },
};
export function accountIssueMessage(name: string, recipient: "ambassador" | "referrer", issue: AccountIssue, details: string, profile?: string | null, referralPartner?: string | null) {
  const partner = referralPartner?.trim();
  const intro = recipient === "ambassador"
    ? `Your LinkedIn account was provided to us via referral${partner ? ` by our referral partner, ${partner}` : " through our referral programme"}.`
    : `${name}'s LinkedIn account was provided to us via referral${partner ? ` by ${partner}` : " through our referral programme"}. We are contacting you as the referral partner for this account.`;
  const template = ACCOUNT_ISSUES[issue];
  return { subject: "Monthly LinkedVelocity Payments Suspended", text:
    `Hi${recipient === "ambassador" ? ` ${name}` : partner ? ` ${partner}` : ""},\n\n${intro}${profile ? `\nLinkedIn account: ${profile}` : ""}\n\n${template.problem}${issue === "other" ? `\n\n${details.trim()}` : ""}\n\nMonthly LinkedVelocity payments for this account are suspended until the issue is resolved and our team confirms access has been restored.\n\n${recipient === "referrer" ? `Please contact ${name} and help them complete the following steps:` : "Please complete the following steps:"}\n${template.steps}\n\nPlease do not send passwords or one-time codes by email. Reply if you need help. Payments will resume once the issue is rectified and access is confirmed.\n\nThank you,\nThe LinkedVelocity team` };
}
