export const ONBOARDING_ISSUES = {
  application_incomplete: { label: "Application not complete", action: "Your application has been started, but onboarding is not complete. You can either book a meeting with our team at https://calendly.com/linkedvelocity-info/30min, or return to your onboarding wizard to add and verify the assigned Ortus / LinkedVelocity email, set it as primary, and complete the 2FA step. If you are setting up your own account, sign in at https://linkedvelocity.com/login, open your dashboard, and choose Continue setup under Accounts I’m Renting Out. If you are helping someone you referred, continue from their account in your referral portal." },
  email_added: { label: "Email not added", action: "Open LinkedIn → Settings & Privacy → Sign in & security → Email addresses. Add the LinkedVelocity email shown below and complete verification." },
  email_primary: { label: "Email not primary", action: "Open LinkedIn → Settings & Privacy → Sign in & security → Email addresses. Set the verified LinkedVelocity email as primary. Keep the original email as a secondary address." },
  twofa: { label: "2FA not set up", action: "Follow https://linkedvelocity.com/guide/two-step-verification to set up authenticator-based two-step verification, then contact our team to complete the secure setup." },
  password: { label: "Password missing / wrong", action: "Check you can sign in to LinkedIn. If needed, reset the password using LinkedIn’s official recovery process, then contact our team to arrange a secure update." },
  restricted: { label: "Account restricted", action: "Open LinkedIn on your own phone and follow its identity-verification steps. See https://linkedvelocity.com/guide/restricted-account, then let our team know when the restriction is cleared." },
  other: { label: "Other", action: "" },
} as const;
export type OnboardingIssue = keyof typeof ONBOARDING_ISSUES;
export function onboardingIssueMessage(issue: OnboardingIssue, recipient: "ambassador" | "referrer", name: string, profile: string | null, lvEmail: string | null, details: string, referrerResumeUrl?: string | null) {
  const item = ONBOARDING_ISSUES[issue];
  return { subject: `LinkedVelocity onboarding: ${item.label}`, text: `Hi,\n\nWe need help completing onboarding for ${name}${profile ? ` (${profile})` : ""}.\n\nIssue: ${item.label}\n${recipient === "referrer" ? `Please help ${name} complete these steps:\n` : ""}${issue === "other" ? details : item.action}${issue === "application_incomplete" && recipient === "referrer" && referrerResumeUrl ? `\n\nContinue onboarding for ${name}:\n${referrerResumeUrl}\nThis private link opens their saved setup where you left off. Keep it private to your referral team.` : ""}\n\nLinkedVelocity email: ${lvEmail || "Please confirm the assigned email with our team."}\n\nReply when this is done, or let us know where you are stuck. We’ll check the account and continue onboarding.\n\nThank you,\nThe LinkedVelocity team` };
}
