const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
function load(file,mocks={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(n=>mocks[n]||require(n),m,m.exports);return m.exports;}
const config=load('src/lib/referral-currency.ts');const display=load('src/lib/display-currency.ts',{'./referral-currency':config,'./utils':{PHP_PER_USD:58}});
test('programme offers use existing agreed prices in selected order',()=>{assert.equal(display.offerPair(16,1000,'USD'),'$16 (₱1,000)');assert.equal(display.offerPair(16,1000,'PHP'),'₱1,000 ($16)');assert.equal(display.configuredOffer(800,'PHP','USD'),'$13 (₱800)');assert.equal(display.offerRange(8,16,500,1000,'USD'),'$8–$16 (₱500–₱1,000)');});
test('balances preserve their actual amount and label converted values as estimates',()=>{assert.equal(display.balancePair(500,'PHP','USD'),'≈$8.62 (₱500)');assert.equal(display.balancePair(16,'USD','PHP'),'≈₱928 ($16)');assert.equal(display.balanceText('₱1,000 paid','USD'),'≈$17.24 (₱1,000) paid');});
const messages=load('src/lib/account-issue-message.ts');
test('issue emails provide primary email, guides and a real 2FA received date when recorded',()=>{const m=messages.accountIssueMessage('Example','ambassador','email_removed','',null,'Partner',{lv:'assigned@example.com',twoFactorReceivedAt:'2026-09-27T12:00:00Z'}).text;for(const text of ['assigned@example.com','PRIMARY','27 September 2026','guide/primary-email','guide/two-step-verification','replying to this email','not the temporary six-digit code'])assert.ok(m.includes(text),text);});
test('legacy key dates remain explicitly unknown',()=>{assert.ok(messages.accountIssueMessage('Example','ambassador','two_factor','').text.includes('We do not have a recorded date'));});

test('ambassador messages address the owner and their payments directly',()=>{for(const issue of messages.ISSUE_KEYS){const text=messages.accountIssueMessage('Owner','ambassador',issue,'Custom issue',null,'Partner').text;for(const part of ['through a referral from Partner','As the account owner, your monthly','Option 1: Check and resolve it yourself','Option 2: Resolve it together on a call','Our team will test whether we can access your account again','you will start receiving monthly LinkedVelocity payments again'])assert.ok(text.includes(part),part);assert.ok(!text.includes('whether the account owner can'));}});
test('referrer messages ask for help from the owner and identify whose payments resume',()=>{for(const issue of messages.ISSUE_KEYS){const text=messages.accountIssueMessage('Owner','referrer',issue,'Custom issue',null,'Partner').text;for(const part of ['Hi Partner','You provided us with Owner','Owner, as the account owner, will need to look into the account','payments to Owner, the account owner, are suspended','Instructions for Owner:','reply to this email or message us',"access Owner's account again",'Owner will start receiving monthly LinkedVelocity payments again','Option 2: Resolve it together on a call'])assert.ok(text.includes(part),part);assert.ok(!text.includes('your monthly LinkedVelocity payments'));assert.ok(!text.includes('you will start receiving monthly'));}});

test('option one requires all primary email and 2FA checks for every issue',()=>{for(const issue of messages.ISSUE_KEYS){const text=messages.accountIssueMessage('Owner','ambassador',issue,'Custom issue',null,'Partner',{lv:'exact@example.com'}).text;for(const part of ['Complete ALL of these checks before replying','The LinkedVelocity email should be exact@example.com','set as PRIMARY','two-step verification is enabled','changed since it was created or last provided','reset the authenticator setup','provide the new setup key','guide/primary-email','guide/two-step-verification'])assert.ok(text.includes(part),part);}});
