const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
function fixture({authorized=true,removed=false,status='maintenance',rentals=[],secret='JBSWY3DPEHPK3PXP'}={}){let reads=0;let selected;const m={exports:{}};class EmailSetupError extends Error{};const mocks={'@/lib/prisma':{prisma:{linkedInAccount:{findUnique:async args=>{reads++;selected=args;return{status,rentals,twoFactor:secret,removedAt:removed?new Date():null,loginEmail:'owner@example.com'};}}}},'@/lib/primary-email-recovery':{verifiedRecoveryOwner:async()=>{if(!authorized)throw new Error('Forbidden');return'owner-id';}},'@/lib/crypto-creds':{decryptSecret:x=>x},'@/lib/totp':{generateTotp:()=>({code:'123456',expiresIn:20})},'@/lib/onboarding-email-policy':{EmailSetupError}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync('src/lib/owner-sign-in-code.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(n=>mocks[n]||require(n),m,m.exports);return{...m.exports,get reads(){return reads;},get selected(){return selected;}};}
test('unauthorized requests cannot read credential records',async()=>{const f=fixture({authorized:false});await assert.rejects(f.ownerSignInCode('token','owner@example.com'));assert.equal(f.reads,0);});
test('code lookup is scoped to the verified owner and never returns the key',async()=>{const f=fixture();const r=await f.ownerSignInCode('token','owner@example.com');assert.deepEqual(f.selected.where,{id:'owner-id'});assert.deepEqual(Object.keys(r).sort(),['address','code','expiresAt']);assert.equal(r.code,'123456');assert.ok(r.expiresAt>Date.now());});
test('removed accounts and invalid or missing keys return no code',async()=>{for(const opts of [{removed:true},{secret:''},{secret:'contact the owner'}])await assert.rejects(fixture(opts).ownerSignInCode('token','owner@example.com'));});

test('knowing another login email cannot select another account',async()=>{await assert.rejects(fixture().ownerSignInCode('token','someone-else@example.com'));await assert.rejects(fixture().ownerSignInCode('token',''));assert.equal((await fixture().ownerSignInCode('token',' OWNER@EXAMPLE.COM ')).code,'123456');});

test('code tool denies available, rented, trial and retired accounts and any active rental',async()=>{for(const status of ['available','rented','trial','retired','removed'])await assert.rejects(fixture({status}).ownerSignInCode('token','owner@example.com'));await assert.rejects(fixture({status:'maintenance',rentals:[{id:'rental'}]}).ownerSignInCode('token','owner@example.com'));for(const status of ['maintenance','under_review','under_construction','construction_immature','unavailable'])assert.equal((await fixture({status}).ownerSignInCode('token','owner@example.com')).code,'123456');});
