const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
function fixture({accountId='owner-id',loginEmail='owner@example.com',privateAuthorized=true,authorized=true,removed=false,status='maintenance',restrictedAt=null,twoFactorResetNeeded=false,rentals=[],secret='JBSWY3DPEHPK3PXP'}={}){let reads=0;let selected;const m={exports:{}};class EmailSetupError extends Error{};const mocks={'@/lib/account-code-link':{readAccountCodeLink:()=> {if(!privateAuthorized)throw new Error('Invalid or expired link');return accountId;}},'@/lib/prisma':{prisma:{linkedInAccount:{findUnique:async args=>{reads++;selected=args;return{status,restrictedAt,twoFactorResetNeeded,rentals:rentals.filter(r=>!args.select.rentals.where.isShadow ? !r.isShadow : true),twoFactor:secret,removedAt:removed?new Date():null,loginEmail};}}}},'@/lib/primary-email-recovery':{verifiedRecoveryOwner:async()=>{if(!authorized)throw new Error('Forbidden');return accountId;}},'@/lib/crypto-creds':{decryptSecret:x=>x},'@/lib/totp':{generateTotp:()=>({code:'123456',expiresIn:20})},'@/lib/onboarding-email-policy':{EmailSetupError}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync('src/lib/owner-sign-in-code.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(n=>mocks[n]||require(n),m,m.exports);return{...m.exports,get reads(){return reads;},get selected(){return selected;}};}
test('unauthorized requests cannot read credential records',async()=>{const f=fixture({authorized:false});await assert.rejects(f.ownerSignInCode('token','owner@example.com'));assert.equal(f.reads,0);});
test('code lookup is scoped to the verified owner and never returns the key',async()=>{const f=fixture();const r=await f.ownerSignInCode('token','owner@example.com');assert.deepEqual(f.selected.where,{id:'owner-id'});assert.deepEqual(Object.keys(r).sort(),['address','code','expiresAt']);assert.equal(r.code,'123456');assert.ok(r.expiresAt>Date.now());});
test('removed accounts and invalid or missing keys return no code',async()=>{for(const opts of [{removed:true},{secret:''},{secret:'contact the owner'}])await assert.rejects(fixture(opts).ownerSignInCode('token','owner@example.com'));});

test('knowing another login email cannot select another account',async()=>{await assert.rejects(fixture().ownerSignInCode('token','someone-else@example.com'));await assert.rejects(fixture().ownerSignInCode('token',''));assert.equal((await fixture().ownerSignInCode('token',' OWNER@EXAMPLE.COM ')).code,'123456');});

test('code tool denies available, rented, trial and retired accounts and any active rental',async()=>{for(const status of ['available','rented','trial','retired','removed'])await assert.rejects(fixture({status}).ownerSignInCode('token','owner@example.com'));await assert.rejects(fixture({status:'maintenance',rentals:[{id:'rental'}]}).ownerSignInCode('token','owner@example.com'));for(const status of ['maintenance','under_review','under_construction','construction_immature','unavailable'])assert.equal((await fixture({status}).ownerSignInCode('token','owner@example.com')).code,'123456');});
test('private links obey the same rented and available account exclusions',async()=>{for(const status of ['available','rented','trial'])await assert.rejects(fixture({status}).privateOwnerSignInCode('private-link','owner@example.com'));await assert.rejects(fixture({rentals:[{id:'active'}]}).privateOwnerSignInCode('private-link','owner@example.com'));assert.equal((await fixture().privateOwnerSignInCode('private-link','owner@example.com')).code,'123456');await assert.rejects(fixture().privateOwnerSignInCode('private-link','other@example.com'));});

test('restricted maintenance accounts allow shadow assignments but never customer rentals',async()=>{const f=fixture({status:'available',restrictedAt:new Date(),rentals:[{id:'shadow',isShadow:true}]});assert.equal((await f.privateOwnerSignInCode('link','owner@example.com')).code,'123456');assert.equal(f.selected.select.rentals.where.isShadow,false);await assert.rejects(fixture({status:'available',restrictedAt:new Date(),rentals:[{id:'customer',isShadow:false}]}).privateOwnerSignInCode('link','owner@example.com'));assert.equal((await fixture({status:'available',twoFactorResetNeeded:true}).privateOwnerSignInCode('link','owner@example.com')).code,'123456');await assert.rejects(fixture({status:'available'}).privateOwnerSignInCode('link','owner@example.com'));await assert.rejects(fixture({status:'rented',restrictedAt:new Date()}).privateOwnerSignInCode('link','owner@example.com'));});

const dexter = {accountId:'4c86793b-6a70-4e05-99f0-601f798c0025',loginEmail:'dexter.obias@lotuspost.co.uk',status:'rented',rentals:[{id:'real-rental',isShadow:false}]};
test('Dexter can retrieve a code with his valid private link while rented',async()=>{
 const f=fixture(dexter);const r=await f.privateOwnerSignInCode('link',dexter.loginEmail);
 assert.equal(r.code,'123456');assert.equal(r.address,dexter.loginEmail);
 assert.deepEqual(Object.keys(r).sort(),['address','code','expiresAt']);
});
test('Dexter exception requires the exact account, matching email and valid private link',async()=>{
 for(const overrides of [{accountId:'different-account'},{loginEmail:'different@example.com'},{privateAuthorized:false},{removed:true},{status:'retired'},{status:'removed'}])
  await assert.rejects(fixture({...dexter,...overrides}).privateOwnerSignInCode('link',dexter.loginEmail));
 await assert.rejects(fixture(dexter).privateOwnerSignInCode('link','other@example.com'));
 await assert.rejects(fixture(dexter).ownerSignInCode('recovery-token',dexter.loginEmail));
 assert.equal((await fixture(dexter).privateOwnerSignInCode('link',' DEXTER.OBIAS@LOTUSPOST.CO.UK ')).code,'123456');
});
