const {test}=require('node:test'), assert=require('node:assert/strict'), fs=require('fs'),ts=require('typescript');
function load(file,mocks){const m={exports:{}};new Function('require','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(n=>{if(!(n in mocks))throw Error(n);return mocks[n]},m.exports);return m.exports;}
function handover(prisma,extras={}){return load('src/lib/shadow-handover.ts',{'@/lib/prisma':{prisma},'@/lib/rental-access':{revokeRentalAccess:async()=>[]},'@/services/email':{sendShadowYieldEmail:async()=>{}},'@/lib/stripe':{stripe:{subscriptions:{update:async()=>{},cancel:async()=>{}}}},'@/services/gologin':{},...extras});}
test('paid month is clamped at month end and starts from handover time',()=>{const h=handover({});assert.equal(h.paidMonthEnd(new Date('2026-01-31T10:30:00Z')).toISOString(),'2026-02-28T10:30:00.000Z');});
test('schedule keeps access, disables shadow renewal, holds paid month and credits exactly once',async()=>{
 const customer={id:'real'},shadow={id:'shadow',userId:'user',notes:null};let credit=0,refunds=0,real;
 const tx={$executeRaw:async()=>{},rental:{findFirst:async()=>customer,findMany:async()=>[shadow],update:async({where,data})=>{if(where.id==='shadow')Object.assign(shadow,data);else real=data;}},transaction:{findFirst:async()=>({amount:-25}),create:async()=>{refunds++}},user:{update:async({data})=>{credit+=data.usdcBalance.increment}}};
 const h=handover({$transaction:async fn=>fn(tx)});await h.scheduleShadowHandover('account');const due=shadow.shadowExitAt;await h.scheduleShadowHandover('account');assert.equal(credit,25);assert.equal(refunds,1);assert.equal(shadow.autoRenew,false);assert.equal(real.status,'pending_access');assert.equal(real.currentPeriodEnd,null);assert.equal(+real.handoverAt,+due);assert.ok(+due-Date.now()>6.99*86400000);assert.equal(shadow.status,undefined);
});
function access(rental,count=0,unshare=async()=>{}){let shared=0,updates=[];const prisma={rental:{findUnique:async()=>rental,count:async()=>count,update:async a=>updates.push(a.data)},linkedInAccount:{update:async()=>{}}};const api=load('src/lib/rental-access.ts',{'@/lib/prisma':{prisma},'@/lib/shadow-handover':{paidMonthEnd:handover({}).paidMonthEnd},'@/lib/stripe':{stripe:{subscriptions:{update:async()=>{}}}},'@/services/gologin':{tokenForAccount:()=>'',workspaceForAccount:()=>null,shareProfile:async()=>{shared++;return{id:'share'}},unshareProfile:unshare,getPublicShareLink:async()=>({publicUrl:'https://example.test/new-share'})},'@/generated/prisma/client':{}});return{api,updates,shared:()=>shared};}
const base={id:'r',linkedinAccountId:'a',isShadow:false,status:'pending_access',gologinShareIds:[],user:{email:'renter@example.test'},linkedinAccount:{gologinProfileId:'p'}};
test('no incoming access before deadline or while shadow access remains',async()=>{for(const [date,count]of [[new Date(Date.now()+86400000),0],[new Date(0),1],[null,1]]){const a=access({...base,handoverAt:date},count);await assert.rejects(a.api.grantRentalAccess('r'));assert.equal(a.shared(),0);}});
test('handover grant starts a full paid month and clears preparation',async()=>{const a=access({...base,handoverAt:new Date(0)});await a.api.grantRentalAccess('r');const final=a.updates.at(-1);assert.equal(final.status,'active');assert.equal(final.handoverAt,null);assert.ok(+final.currentPeriodEnd-+final.startDate>=28*86400000);});
test('failed revocation retains its share id for retry',async()=>{const a=access({...base,gologinShareIds:[{email:'renter@example.test',shareId:'s'}]},0,async()=>{throw Error('denied')});const result=await a.api.revokeRentalAccess('r');assert.equal(result[0].ok,false);assert.equal(a.updates[0].gologinShareIds[0].shareId,'s');assert.equal(a.updates[0].accessRevokedAt,undefined);});
